### PR TITLE
DOC: Bump disk requirement in README.md example job as it currently fails to run

### PR DESCRIPTION
**Pull request by jgardner8**
Example task fails with 10MB of disk space, increased to 40MB.

### CODE REVIEW

**Comment by jgardner8** [comment]
Good point, how's the new one?

**Comment by jgardner8** [comment]
Good point, there was a second line which had more detail but it's not displayed very well in GitHub, so it could be clearer. How is the revised one?

**Comment by rimmington** [comment]
@jgardner8 Now it's a bit too long. Drop the "as it ..." bit :grin:

**Comment by jgardner8** [comment]
done

**Pull request merged**
